
BASE=$(PWD)

TARGET=octo
MODULES=$(TARGET) \
	Add Atom BinaryOperator Divide Integer Intrinsic Multiply \
        OctoConfig OctoParser OctoModuleLoader OctoProcess OctoSourceLibrary \
	ParseTreeToCode Primitive Runtime Scope Sequence StandardLibrary Subtract Value \
	run_program testing

LIBRARIES=general parsing system types memory

include ./make.app

