
BASE=..

LIBRARY=parsing
MODULES=Context GrammarParser Matcher ParseResult ParseTree ParseTreeWalker Rule StandardRules \
	MatchChoice MatchRegex MatchRepeated MatchSequence MatchString PcrePattern ResultTransformer Token
INCLUDING=general memory
OTHERLIBS=-lpcre

include ../make.lib

